version: "3.7"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    volumes:
      - "mysql-db:/var/lib/mysql"
    ports:
      - 3306:3306
  app:
    image: node:10.12
    depends_on:
      - db
    volumes:
      - ".:/app"
    working_dir: "/app"
volumes:
  mysql-db:
    driver: local  
